source "https://supermarket.getchef.com"
source 'https://supermarket.chef.io'

cookbook 'apt'
cookbook 'yum'
cookbook 'bluepill'
cookbook 'ark'
cookbook 'build-essential'
cookbook 'openssl'
cookbook 'apache2'
cookbook 'php'
cookbook 'mysql'
cookbook 'application_git'
cookbook 'phpapp', path: 'phpapp_cookbook'
cookbook 'newrelic', path: 'newrelic_cookbook'
cookbook 'phpmyadmin', path: 'phpmyadmin_cookbook'
